<?php

return [
    'site' => [
        'name' => 'Akasha Production',
        'tagline' => 'Concept, création web et écosystème de projets',
        'responsable' => 'Robin Prevent',
        'address_lines' => [
            '50 avenue Frédéric Mistral',
            '83170 Brignoles, France',
        ],
        'phone' => '078148871',
        'contact_email' => 'contact@akashaproduction.com',
        'contact_email_label' => 'nous contacter',
        'facebook_url' => 'https://www.facebook.com/akashaproduction',
        'host' => [
            'name' => 'o2switch',
            'address_lines' => [
                'Chemin des Pardiaux',
                '63000 Clermont-Ferrand, France',
            ],
            'legal_lines' => [
                'SAS au capital de 100 000 €',
                'RCS Clermont-Ferrand 510 909 807',
            ],
            'phone' => '04 44 44 60 40',
            'website' => 'https://www.o2switch.fr',
        ],
    ],
    'navigation' => [
        'presentation' => ['label' => 'Présentation', 'href' => '/'],
        'solutions' => ['label' => 'Nos solutions', 'href' => '/nos-solutions'],
        'contact' => ['label' => 'Contact', 'href' => '/contact'],
        'commander' => ['label' => 'Commander', 'href' => '/commander'],
        'account' => ['label' => 'Mon compte', 'href' => '/mon-compte'],
    ],
    'projects' => [
        [
            'title' => 'CMS Source',
            'url' => 'https://www.cms-source.org',
            'domain' => 'cms-source.org',
            'status' => 'Vérification partielle',
            'description' => 'Notre projet CMS multisite, multilingue, mis à disposition du grand public. Téléchargez et parametrez vous même votre installation.',
        ],
        [
            'title' => 'Mafiaz World',
            'url' => 'https://www.mafiaz.world',
            'domain' => 'mafiaz.world',
            'status' => 'En ligne',
            'description' => 'Le jeu en ligne Ombres & Lumières, de l’univers Mafiaz.World - Création sur serveur VPS dédié avec installation Node.js',
        ],
        [
            'title' => 'Permathèque',
            'url' => 'http://www.permatheque.fr',
            'domain' => 'permatheque.fr',
            'status' => 'En ligne',
            'description' => 'Association et espace collaboratif consacré à la permaculture, avec ressources, outils, vidéos, agenda et apprentissage terrain.',
        ],
        [
            'title' => 'Vivre en Autonomie',
            'url' => 'https://www.vivre-en-autonomie.fr',
            'domain' => 'vivre-en-autonomie.fr',
            'status' => 'En ligne',
            'description' => 'Ressources thématiques sur l’autonomie, l’habitat et les pratiques concrètes pour vivre plus indépendamment.',
        ],
        [
            'title' => 'Conseil Ayurveda',
            'url' => 'https://www.conseil-ayurveda.fr',
            'domain' => 'conseil-ayurveda.fr',
            'status' => 'En ligne',
            'description' => 'Recommandations ayurvédiques, bilans, consultations, soins et retraites centrés sur l’hygiène de vie et l’équilibre global.',
        ],
        [
            'title' => 'On Apprend Tous Les Jours',
            'url' => 'https://www.onapprendtouslesjours.fr',
            'domain' => 'onapprendtouslesjours.fr',
            'status' => 'En ligne',
            'description' => 'Plateforme éducative pour apprendre le français en vidéo, avec lecture, écriture, sons et vocabulaire pour petits et grands.',
        ],
        [
            'title' => 'Eau Dynamisée',
            'url' => 'https://www.eau-dynamisee.com',
            'domain' => 'eau-dynamisee.com',
            'status' => 'En attente',
            'description' => 'Projet actuellement en attente de début d’activité, destiné à présenter l’offre autour de l’eau dynamisée.',
        ],
        [
            'title' => 'Atlas Access Immo',
            'url' => 'https://www.atlas-access.immo',
            'domain' => 'atlas-access.immo',
            'status' => 'En ligne',
            'description' => 'Investissement immobilier et installation au Maroc avec accès facilité, paiement différé et projets VEFA à Marrakech.',
        ],
        [
            'title' => 'Épanouissement Amoureux',
            'url' => 'https://www.epanouissement-amoureux.fr',
            'domain' => 'epanouissement-amoureux.fr',
            'status' => 'En ligne',
            'description' => 'Ressources et accompagnement pour cultiver des relations épanouissantes, renforcer la communication et nourrir la vie de couple.',
        ],
    ],
    'catalog' => [
        'creation' => [
            'showcase' => [
                'label' => 'Site vitrine multilingue 3 pages',
                'amount' => 50,
                'headline' => 'Création vitrine',
                'features' => ['3 pages structurées', 'Version multilingue', 'Design responsive premium'],
            ],
            'complex' => [
                'label' => 'Site complexe 9 pages + 3 modules + base de données',
                'amount' => 500,
                'headline' => 'Création complexe',
                'features' => ['9 pages éditoriales', 'Commerce, newsletter, blog', '1 base de données'],
            ],
            'custom' => [
                'label' => 'Création personnalisée sur devis',
                'amount' => 0,
                'headline' => 'Création personnalisée',
                'features' => ['Étude détaillée', 'Architecture spécifique', 'Proposition sur mesure'],
            ],
        ],
        'hosting' => [
            'shared-monthly' => [
                'label' => 'Serveur mutualisé mensuel',
                'amount' => 8,
                'headline' => 'Mutualisé',
                'suffix' => '/ mois',
            ],
            'shared-yearly' => [
                'label' => 'Serveur mutualisé annuel',
                'amount' => 88,
                'headline' => 'Mutualisé annuel',
                'suffix' => '/ an',
            ],
            'vps' => [
                'label' => 'VPS dédié',
                'amount' => 200,
                'headline' => 'VPS dédié',
                'suffix' => '/ mois',
            ],
            'cloud' => [
                'label' => 'Cloud personnalisé sur devis',
                'amount' => 0,
                'headline' => 'Cloud',
                'suffix' => '',
            ],
        ],
        'domain' => [
            'subdomain' => [
                'label' => 'Sous-domaine offert',
                'amount' => 0,
            ],
            'custom-domain' => [
                'label' => 'Nom de domaine personnalisé',
                'amount' => 18,
            ],
        ],
        'pack_prices' => [
            'showcase:shared-yearly' => 120,
            'complex:shared-yearly' => 550,
            'showcase:vps' => 230,
            'complex:vps' => 675,
        ],
        'quote_questions' => [
            'Objectif principal' => ['Site vitrine', 'E-commerce', 'Blog', 'Espace membre', 'À étudier'],
            'Style recherché' => ['Sobre et premium', 'Nature et bien-être', 'Institutionnel', 'Éditorial', 'À étudier'],
            'Contenus disponibles' => ['J’ai déjà mes contenus', 'J’ai besoin d’aide', 'Traductions à prévoir', 'Photos à produire', 'À étudier'],
            'Délai souhaité' => ['Urgent', '1 mois', '2 à 3 mois', 'Souple', 'À étudier'],
            'Fonctions attendues' => ['Newsletter', 'Blog', 'Paiement en ligne', 'Base de données', 'À étudier'],
        ],
        'parent_domains' => [
            'akashaproduction.com',
            'permatheque.fr',
            'vivre-en-autonomie.fr',
            'conseil-ayurveda.fr',
            'onapprendtouslesjours.fr',
            'harmonie-holistique.fr',
            'mafiaz.world',
            'alasourcedeleau.org',
        ],
    ],
    'support' => [
        'departments' => [
            'commercial' => 'Service commercial',
            'technical' => 'Service technique',
        ],
        'topics' => [
            'commercial' => [
                'Demande de devis',
                'Question sur une commande',
                'Paiement ou facturation',
                'Pack, combo ou promotion',
                'Nom de domaine',
                'Hébergement',
                'Autre demande commerciale',
            ],
            'technical' => [
                'Incident site web',
                'Bug d’affichage',
                'Accès FTP / SSH / base de données',
                'Nom de domaine ou DNS',
                'Email ou délivrabilité',
                'Performance ou sécurité',
                'Autre demande technique',
            ],
        ],
        'priorities' => [
            'normal' => 'Normale',
            'high' => 'Haute',
            'urgent' => 'Urgente',
        ],
        'statuses' => [
            'open' => 'Ouvert',
            'in-progress' => 'En cours',
            'answered' => 'Répondu',
            'closed' => 'Clos',
        ],
    ],
    'subprojects' => [
        'CMS Source',
        'Ombres & Lumières',
        'Permathèque',
        'Vivre en Autonomie',
        'Conseil Ayurveda',
        'On Apprend Tous Les Jours',
        'Location Vente',
        'Université Védique',
        'À La Source De L’Eau',
        'Épanouissement Amoureux',
        'Eau Dynamisée',
        'Harmonie Holistique',
        'Atlas Access Immo',
    ],
    'admin_email' => 'contact@akashaproduction.com',
    'admin_aliases' => [
        'contact@akashaproduction.com',
        'contact@permatheque.org',
    ],
    // Hash password_hash(PASSWORD_DEFAULT) — vide = admin désactivé.
    'admin_password_hash' => '',
    'stripe_secret_key' => '',
    'stripe_webhook_secret' => '',
];
